services:
  vendor_db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - vendors_postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"

  vendor_service:
    build: ./services/vendor-service
    command: gunicorn vendor_service.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    ports:
      - "8000:8000"
    depends_on:
      - vendor_db
    environment:
      POSTGRES_NAME: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: vendor_db
      SECRET_KEY: vendor-secret
      DEBUG: True
      ALLOWED_HOSTS: localhost

volumes:
  vendors_postgres_data: