# Generated by Django 5.1.6 on 2025-08-06 10:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('payload', models.JSONField()),
                ('headers', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Payment Webhook Log',
                'verbose_name_plural': 'Payment Webhook Logs',
                'db_table': 'payment_webhook_logs',
                'indexes': [models.Index(fields=['processed'], name='payment_web_process_385493_idx'), models.Index(fields=['created_at'], name='payment_web_created_e04c0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('user_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription'), ('order', 'Order')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'), models.Index(fields=['user_id', 'status'], name='transaction_user_id_08c743_idx')],
            },
        ),
    ]
