# Generated by Django 5.1.6 on 2025-08-06 18:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('monthly_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('yearly_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('yearly_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('name', 'payment_method', 'interval'), name='unique_payment_method_name')],
            },
        ),
    ]
