# Generated by Django 5.1.6 on 2025-08-04 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
                ('monthly_price', models.FloatField(blank=True, null=True)),
                ('yearly_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of features in the plan, stored as a JSON array.')),
                ('button_text', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=200)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user_id', models.UUIDField(help_text='User ID from Auth Service', verbose_name='User Id')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Physical Address')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'indexes': [models.Index(fields=['name'], name='vendors_name_a8eecc_idx'), models.Index(fields=['email'], name='vendors_email_c977c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10, verbose_name='Billing Cycle')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='inactive', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_plans', to='vendors.subscriptionplan', verbose_name='Subscription Plan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor Plan',
                'verbose_name_plural': 'Vendor Plans',
                'db_table': 'vendor_plans',
            },
        ),
    ]
