# Generated by Django 5.1.6 on 2025-05-29 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user_id', models.UUIDField(help_text='User ID from Auth Service', verbose_name='User Id')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Physical Address')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'indexes': [models.Index(fields=['name'], name='vendors_name_a8eecc_idx'), models.Index(fields=['email'], name='vendors_email_c977c0_idx')],
            },
        ),
    ]
