# Generated by Django 5.1.6 on 2025-08-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorplan',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_plans', to='vendors.subscriptionplan', verbose_name='Subscription Plan'),
        ),
        migrations.AlterField(
            model_name='vendorplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='vendorplan',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='vendors.vendor', verbose_name='Vendor'),
        ),
    ]
