# Generated by Django 5.1.6 on 2025-08-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendorplan_plan_alter_vendorplan_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_plans', to='vendors.subscriptionplan', verbose_name='Subscription Plan'),
        ),
        migrations.AlterField(
            model_name='vendorplan',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='vendors.vendor', verbose_name='Vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendorplan',
            constraint=models.UniqueConstraint(fields=('vendor', 'plan'), name='unique_vendor_plan'),
        ),
    ]
